### PR TITLE
feat: Sync actions of the plugin configuration with build settings

### LINKED ISSUE #48: Sync actions of the plugin configuration (add/remove scene) with build settings
When we add or remove the scene from the plugin settings - this is an explicit action, so we can add or remove the scene from the build setting and display notification.

When Editor build settings is 100% in sycn we can just clean & rebuild it
When it's out of sync we will just add / remove the scene without carrying for the order.

### PR DESCRIPTION
**Pull request by ghost**
## Purpose of this PR
When Editor build settings is 100% in sync we just clean & rebuild scenes from Build Settings

## Testing status
* No tests have been added.

### Manual testing status
Ok

## Dependencies
Depend on changes of [#59](https://github.com/StansAssets/com.stansassets.scene-management/pull/59) PR

### CODE REVIEW

**Comment by stan-osipov** [comment]
It is also very important to preserve scene order.
I would say we really need to make sure that scene that is set as scene 0 in our configurations is also set to 0 in the editor build settings. 
For another scene, I don't think that exact order would be really important, but let's say it's nice to have.

Build_Settings_and_SampleScene_-_Plugins_-_Windows__Mac__Linux_-_Unity_2021_3_12f1_Personal__Personal___Metal_

**Review by stan-osipov — CHANGES_REQUESTED** [review]
please see the comment about scene order.

**Comment by stan-osipov** [comment]
When auto Sync can not be executed:

- When the editor builds setting missing scenes   (error)
- When the editor build setting has more scenes than the user specified in the config (warning)
- When the editor builds the setting first scene does not match our config  (warning)

**Comment by stan-osipov** [comment]
There is a bug when the editor platfrom does not match any platform in the configuration
WiFi_and_Clock_and_BentoBox_and_Item-0

**Comment by stan-osipov** [comment]
SampleScene_-_Plugins_-_Windows__Mac__Linux_-_Unity_2021_3_12f1_Personal__Personal___Metal_
Would be nice to make sure we have room for the message.

**Comment by stan-osipov** [comment]
There are a few issues I see with the nonactive config.

* We don't have any visual indication which config is active (this can be done as a separate PR)
* I do have color indication that scene is missing even not in our active config - which is very good I think
* But in my non active config I do have duplicated scene and I don't have duplicates notifications

SampleScene_-_Plugins_-_Windows__Mac__Linux_-_Unity_2021_3_12f1_Personal__Personal___Metal_

**Comment by stan-osipov** [comment]
another bug
Cursor

**Comment by stan-osipov** [comment]
Please do small changes to the warning window:
Screenshot_15_02_2023__12_18


* Skin (should continue to the play mode)
* Open Scene Management (should open scene manga, ent settings, and exit play mode)
* Don't show again - no changes

**Comment by yurii-lunha-stansassets** [comment]
- Improved & fixed auto-sync actions. For this was replaced "lists" drawing methods and the user interface has become slightly different than before.
- Changed repetitive scenes logic. Now, if scene doesn't intersect with default scenes we can have the same scene for two target platforms. 
- Also fixed bugs that I didn't saw before.

Screenshot 2023-02-21 121752
Screenshot 2023-02-21 124842
Screenshot 2023-02-21 124700

**Comment by yurii-lunha-stansassets** [comment]
Also, active target platform is highlighted (bold text) and Editor too.

**Pull request merged**
